//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapStoneCraftxProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CapStoneProjectEntities5 : DbContext
    {
        public CapStoneProjectEntities5()
            : base("name=CapStoneProjectEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cellar> Cellars { get; set; }
        public virtual DbSet<Trade> Trades { get; set; }
        public virtual DbSet<Beer> Beers { get; set; }
        public virtual DbSet<Member> Members { get; set; }
    }
}
