//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapStoneCraftxProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trade
    {
        public int Id { get; set; }
        public int SendingMemberId { get; set; }
        public int ReceivingMemberId { get; set; }
        public int SendingBeerId { get; set; }
        public int ReceiverBeerId { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string SendingComments { get; set; }
        public string ReceivingComments { get; set; }
    
        public virtual Cellar Cellar { get; set; }
        public virtual Cellar Cellar1 { get; set; }
        public virtual Beer Beer { get; set; }
        public virtual Beer Beer1 { get; set; }
    }
}
